server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/reading_contest
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true